# Generated by Django 4.2.5 on 2023-09-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('ilosc', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('jednostka_miary', models.CharField(choices=[('SZT', 'szt.'), ('KG', 'kg'), ('G', 'g'), ('ML', 'ml.')], default='SZT.', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_edytowania', models.DateTimeField(auto_now=True)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('skladniki', models.ManyToManyField(to='menu.skladnik')),
            ],
        ),
    ]
