# Generated by Django 4.2.5 on 2023-09-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skladnik',
            name='ilosc',
        ),
        migrations.RemoveField(
            model_name='skladnik',
            name='jednostka_miary',
        ),
    ]
